version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/project-bsr?authSource=admin
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_ACCESS_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=7d
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_BUCKET_NAME=your-bucket-name
      - BCRYPT_SALT_ROUNDS=10
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - project-bsr-network

  mongodb:
    image: mongo:latest
    container_name: project-bsr-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - project-bsr-network

networks:
  project-bsr-network:
    driver: bridge

volumes:
  mongodb_data: 